### ISSUE TITLE
Awesome work! Might be unnecessary after Joplin 2.5

### ISSUE THREAD

**Issue by jt196** [pickerin/joplin-update-frontmatter#2]
@pickerin - just tested this and it all works really well. Have been thinking about testing Obsidian, so preserving the metadata was a primary consideration. 

As of [Joplin 2.5](https://discourse.joplinapp.org/t/joplin-v2-5-is-available-for-desktop-and-mobile/21377), there is an export option for "MD + Front Matter", which gives a nice export formatted thus:

```YAML
---
title: Your note title
updated: 2021-10-23 11:02:00Z
created: 2021-10-23 11:02:00Z
source: https://redd.it/qe2byu
latitude: 51.84375756
longitude: -0.13620712
altitude: 143.1049
tags:
  - audio
  - bookshelf
---
```
